Repository grafana/alerting, pull requests merged in 2023-04, with the labels that each got.

#73 Replace incorrect usage of term "receivers" to "integrations"
  notify/factory_test.go
  notify/grafana_alertmanager.go
  notify/grafana_alertmanager_metrics.go
  notify/grafana_alertmanager_test.go
  notify/receivers.go
  notify/receivers_test.go
Labels: enhancement, kata:am_unify

#78 Fixes Opsgenie Create Alert failure when external image URL attached
  receivers/opsgenie/opsgenie.go
Labels: bug

#79 Rename image.ImageStore to image.Provider
  images/images.go
  images/testing.go
  images/util_test.go
  images/utils.go
  notify/factory.go
  notify/factory_test.go
  receivers/alertmanager/alertmanager.go
  receivers/alertmanager/alertmanager_test.go
  receivers/discord/discord.go
  receivers/discord/discord_test.go
  receivers/email/email.go
  receivers/email/email_test.go
  receivers/googlechat/googlechat.go
  receivers/googlechat/googlechat_test.go
  receivers/kafka/kafka.go
  receivers/kafka/kafka_test.go
  receivers/opsgenie/opsgenie.go
  receivers/opsgenie/opsgenie_test.go
  receivers/pagerduty/pagerduty.go
  receivers/pushover/pushover.go
  receivers/pushover/pushover_test.go
  receivers/sensugo/sensugo.go
  receivers/sensugo/sensugo_test.go
  receivers/slack/slack.go
  receivers/slack/slack_test.go
  receivers/teams/teams.go
  receivers/teams/teams_test.go
  receivers/telegram/telegram.go
  receivers/telegram/telegram_test.go
  receivers/threema/threema.go
  receivers/threema/threema_test.go
  receivers/victorops/victorops.go
  receivers/victorops/victorops_test.go
  receivers/webex/webex.go
  receivers/webex/webex_test.go
  receivers/webhook/webhook.go
  receivers/webhook/webhook_test.go
Labels: kata:am_unify

#80 Describe methods to get an image URL/bytes
  images/images.go
  images/testing.go
  images/utils.go
Labels: kata:am_unify

#77 Add template testing functionality
  notify/alerts.go
  notify/grafana_alertmanager.go
  notify/receivers.go
  notify/templates.go
  notify/templates_test.go
  templates/template_data.go
  templates/util.go
  templates/util_test.go
Labels: enhancement
