Repository grafana/alerting, pull requests merged in 2023-03, with the labels that each got.

#62 Parse notifier configs without creation of notifiers
  notify/factory.go
  notify/receivers.go
  notify/receivers_test.go
  receivers/alertmanager/config_test.go
  receivers/alertmanager/testing.go
  receivers/dinding/config_test.go
  receivers/dinding/testing.go
  receivers/discord/config_test.go
  receivers/discord/testing.go
  receivers/email/config_test.go
  receivers/email/testing.go
  receivers/factory.go
  receivers/googlechat/config_test.go
  receivers/googlechat/testing.go
  receivers/kafka/config_test.go
  receivers/kafka/testing.go
  receivers/line/config_test.go
  receivers/line/testing.go
  receivers/opsgenie/config_test.go
  receivers/opsgenie/testing.go
  receivers/pagerduty/config_test.go
  receivers/pagerduty/testing.go
  receivers/pushover/config_test.go
  receivers/pushover/testing.go
  receivers/sensugo/config_test.go
  receivers/sensugo/testing.go
  receivers/slack/config_test.go
  receivers/slack/testing.go
  receivers/teams/config_test.go
  receivers/teams/testing.go
  receivers/telegram/config_test.go
  receivers/telegram/testing.go
  receivers/testing/testing.go
  receivers/threema/config_test.go
  receivers/threema/testing.go
  receivers/victorops/config_test.go
  receivers/victorops/testing.go
  receivers/webex/config_test.go
  receivers/webex/testing.go
  receivers/webhook/config_test.go
  receivers/webhook/testing.go
  receivers/wecom/config_test.go
  receivers/wecom/testing.go
Labels: enhancement, kata:am_unify

#66 Fix nflog maintenance file path
  notify/grafana_alertmanager.go
Labels: bug

#71 Use type alias for Template
  notify/factory.go
  notify/grafana_alertmanager.go
  notify/testing.go
  receivers/dinding/dingding.go
  receivers/discord/discord.go
  receivers/email/email.go
  receivers/email/email_test.go
  receivers/googlechat/googlechat.go
  receivers/kafka/kafka.go
  receivers/line/line.go
  receivers/opsgenie/opsgenie.go
  receivers/pagerduty/pagerduty.go
  receivers/pushover/pushover.go
  receivers/sensugo/sensugo.go
  receivers/slack/slack.go
  receivers/teams/teams.go
  receivers/telegram/telegram.go
  receivers/threema/threema.go
  receivers/victorops/victorops.go
  receivers/webex/webex.go
  receivers/webhook/webhook.go
  receivers/webhook/webhook_test.go
  receivers/wecom/wecom.go
  templates/default_template.go
  templates/default_template_test.go
  templates/template_data.go
Labels: kata:am_unify
