Repository grafana/alerting, pull requests merged in 2025-02, with the labels that each got.

#284 Alerting: Fix token-based Slack image upload to work with channel names
  receivers/slack/slack.go
  receivers/slack/slack_test.go
Labels: bug

#288 [v11.4.x] Alerting: Fix token-based Slack image upload to work with channel names (#284)
  receivers/slack/slack.go
  receivers/slack/slack_test.go
Labels: backport

#287 [v11.5.x] Alerting: Fix token-based Slack image upload to work with channel names (#284)
  receivers/slack/slack.go
  receivers/slack/slack_test.go
Labels: backport

#290 Try additional scopes when testing templates with root scope fails
  notify/grafana_alertmanager.go
  notify/templates.go
  notify/templates_test.go
Labels: templates

#292 Alerting: Update slack image upload to use new API
  receivers/slack/slack.go
  receivers/slack/slack_test.go
Labels: backport

#293 Alerting: Update slack image upload to use new API
  receivers/slack/slack.go
  receivers/slack/slack_test.go
Labels: backport

#294 Alerting: Update slack image upload to use new API
  receivers/slack/slack.go
  receivers/slack/slack_test.go
Labels: backport

#291 Alerting: Update slack image upload to use new API
  receivers/slack/slack.go
  receivers/slack/slack_test.go
Labels: backport
